[package]
name = "vbinseq"
version = "0.1.0"
edition = "2021"

[dependencies]
bitnuc = "0.2.10"
byteorder = "1.5.0"
memmap2 = "0.9.5"
thiserror = "2.0.11"

[dev-dependencies]
anyhow = "1.0.96"
niffler = "3.0.0"
nucgen = "0.1.2"
paraseq = "0.1.2"
rand = "0.8"
