name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Formatting
        run: cargo fmt --check

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo fmt --check

  test_debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose

  test_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose --release

  example_index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run example
        run: cargo run --release --example index

  example_io:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run example
        run: cargo run --release --example io

  example_parallel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run example
        run: cargo run --release --example parallel
